### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Alex-Davis0** [Alex-Davis0/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create the Html Skeleton
- [x] Setup and link the styles sheet
- [x] Setup the main.js and link it  
- [x] Create the background 
- [x] Make the car 
- [x] Set the start position of the car
